[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@boringcrypto/=node_modules/@boringcrypto/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@rari-capital/=node_modules/@rari-capital/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "prb-math/=node_modules/prb-math/",
    "tapioca-sdk/=node_modules/tapioca-sdk/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
